import React from "react";
import { 
  HiAcademicCap, 
  HiPaperAirplane, 
  HiHome,
  HiDotsHorizontal,
  HiCreditCard,
  HiGlobe,
  HiServer,
  HiOutlineDesktopComputer
} from "react-icons/hi";
import { SiPaypal, SiMastercard, SiAmazon } from "react-icons/si";
import { HiOutlineTemplate } from "react-icons/hi";
import { SiDigitalocean } from "react-icons/si";
import { FaBitcoin, FaGamepad, FaBrain, FaSearch } from "react-icons/fa";
import { BiTransfer, BiShoppingBag } from "react-icons/bi";
import { MdSimCard, MdPhone, MdDomain, MdCloud, MdCode } from "react-icons/md";

export interface Service {
  id: string;
  label: string;
  labelEn?: string;
  href: string;
  icon: React.ReactNode;
  description: string;
  category: "payment" | "travel" | "education" | "crypto" | "other" | "vps" | "premium" | "international";
}

export const services: Service[] = [
  {
    id: "paypal",
    label: "پی پال",
    labelEn: "PayPal",
    href: "/services/paypal",
    icon: React.createElement(SiPaypal, { className: "text-3xl sm:text-4xl md:text-5xl text-[#0070BA]" }),
    description: "نقد کردن درآمد پی پال و پرداخت با پی پال",
    category: "payment",
  },
  {
    id: "mastercard",
    label: "مسترکارت",
    labelEn: "MasterCard",
    href: "/services/mastercard",
    icon: React.createElement(SiMastercard, { className: "text-3xl sm:text-4xl md:text-5xl text-[#EB001B]" }),
    description: "دریافت و استفاده از کارت‌های اعتباری بین‌المللی",
    category: "payment",
  },
  {
    id: "credit-cards",
    label: "کارت های اعتباری",
    labelEn: "Credit Cards",
    href: "/services/credit-cards",
    icon: React.createElement(HiCreditCard, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "دریافت انواع کارت‌های اعتباری بین‌المللی",
    category: "payment",
  },
  {
    id: "crypto",
    label: "ارز دیجیتال",
    labelEn: "Cryptocurrency",
    href: "/services/crypto",
    icon: React.createElement(FaBitcoin, { className: "text-3xl sm:text-4xl md:text-5xl text-[#F7931A]" }),
    description: "خرید و فروش ارزهای دیجیتال",
    category: "crypto",
  },
  {
    id: "transfer",
    label: "حواله ارزی",
    labelEn: "Money Transfer",
    href: "/services/transfer",
    icon: React.createElement(BiTransfer, { className: "text-3xl sm:text-4xl md:text-5xl text-[#1a3760]" }),
    description: "ارسال حواله ارزی به سراسر جهان",
    category: "payment",
  },
  {
    id: "toefl",
    label: "پرداخت تافل",
    labelEn: "TOEFL iBT",
    href: "/services/toefl",
    icon: React.createElement(HiAcademicCap, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "پرداخت هزینه آزمون تافل",
    category: "education",
  },
  {
    id: "gre",
    label: "پرداخت جی آر ای",
    labelEn: "GRE",
    href: "/services/gre",
    icon: React.createElement(HiAcademicCap, { className: "text-3xl sm:text-4xl md:text-5xl text-[#1a3760]" }),
    description: "پرداخت هزینه آزمون GRE",
    category: "education",
  },
  {
    id: "university",
    label: "پرداخت امور دانشگاهی",
    labelEn: "University Payments",
    href: "/services/university",
    icon: React.createElement(HiAcademicCap, { className: "text-3xl sm:text-4xl md:text-5xl text-[#0070BA]" }),
    description: "پرداخت هزینه‌های دانشگاهی و اپلیکیشن فی",
    category: "education",
  },
  {
    id: "tickets",
    label: "بلیط هواپیما، قطار و اتوبوس",
    labelEn: "Tickets",
    href: "/services/tickets",
    icon: React.createElement(HiPaperAirplane, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "خرید بلیط هواپیما، قطار و اتوبوس",
    category: "travel",
  },
  {
    id: "hotel",
    label: "هتل و گردشی تفریحی",
    labelEn: "Hotels & Tourism",
    href: "/services/hotel",
    icon: React.createElement(HiHome, { className: "text-3xl sm:text-4xl md:text-5xl text-[#81B441]" }),
    description: "رزرو هتل و خدمات گردشگری",
    category: "travel",
  },
  {
    id: "embassy",
    label: "وقت سفارت کشورها",
    labelEn: "Embassy Appointments",
    href: "/services/embassy",
    icon: React.createElement(HiGlobe, { className: "text-3xl sm:text-4xl md:text-5xl text-[#1a3760]" }),
    description: "پرداخت هزینه ویزا و رزرو وقت سفارت",
    category: "travel",
  },
  {
    id: "themeforest",
    label: "تم فارست",
    labelEn: "Theme Forest",
    href: "/services/themeforest",
    icon: React.createElement(HiOutlineTemplate, { className: "text-3xl sm:text-4xl md:text-5xl text-[#81B441]" }),
    description: "خرید قالب و افزونه از تم فارست",
    category: "other",
  },
  {
    id: "digitalocean",
    label: "دیجیتال اوشن",
    labelEn: "Digital Ocean",
    href: "/services/digitalocean",
    icon: React.createElement(SiDigitalocean, { className: "text-3xl sm:text-4xl md:text-5xl text-[#0080FF]" }),
    description: "پرداخت هزینه سرویس‌های دیجیتال اوشن",
    category: "other",
  },
  {
    id: "currency",
    label: "نقد کردن درآمد ارزی",
    labelEn: "Currency Exchange",
    href: "/services/currency",
    icon: React.createElement(BiTransfer, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "تبدیل و نقد کردن درآمدهای ارزی",
    category: "payment",
  },
  {
    id: "other",
    label: "سایر پرداخت ها",
    labelEn: "Other Payments",
    href: "/services/other",
    icon: React.createElement(HiDotsHorizontal, { className: "text-3xl sm:text-4xl md:text-5xl text-gray-600" }),
    description: "سایر خدمات پرداخت و ارزی",
    category: "other",
  },
  {
    id: "vps-trading",
    label: "VPS تریدینگ",
    labelEn: "VPS Trading",
    href: "/currency-payment/vps-trading",
    icon: React.createElement(HiServer, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "خرید سرور مجازی ترید با آی‌پی ثابت از مستر پریمیوم هاب؛ پلن‌های رم ۶ و رم ۸، تحویل ۲ تا ۲۴ ساعت کاری",
    category: "vps",
  },
  {
    id: "vps-daily",
    label: "VPS روزانه",
    labelEn: "Daily VPS",
    href: "/currency-payment/vps-daily",
    icon: React.createElement(HiServer, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "سرور مجازی روزانه یک‌روزه و پنج‌روزه از مستر پریمیوم هاب؛ آمریکا و انگلیس، ویندوز، تحویل ۱ تا ۵ ساعت",
    category: "vps",
  },
  {
    id: "vps-usa",
    label: "VPS آمریکا",
    labelEn: "VPS USA",
    href: "/currency-payment/vps-usa",
    icon: React.createElement(HiServer, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "سرور مجازی آمریکا از مستر پریمیوم هاب؛ پلن پایه و حرفه‌ای، آی‌پی آمریکا، تحویل ۲ تا ۲۴ ساعت",
    category: "vps",
  },
  {
    id: "vps-netherlands",
    label: "VPS هلند",
    labelEn: "VPS Netherlands",
    href: "/currency-payment/vps-netherlands",
    icon: React.createElement(HiServer, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "سرور مجازی هلند از مستر پریمیوم هاب؛ پلن پایه و حرفه‌ای، آی‌پی آمستردام، تحویل ۲ تا ۲۴ ساعت",
    category: "vps",
  },
  {
    id: "vps-france",
    label: "VPS فرانسه",
    labelEn: "VPS France",
    href: "/currency-payment/vps-france",
    icon: React.createElement(HiServer, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "سرور مجازی فرانسه از مستر پریمیوم هاب؛ پلن پایه و حرفه‌ای، آی‌پی پاریس، تحویل ۲ تا ۲۴ ساعت",
    category: "vps",
  },
  {
    id: "ai-account",
    label: "خرید اکانت هوش مصنوعی",
    labelEn: "AI Account",
    href: "/currency-payment/ai-account",
    icon: React.createElement(FaBrain, { className: "text-3xl sm:text-4xl md:text-5xl text-green-500" }),
    description: "خرید اکانت‌های پریمیوم هوش مصنوعی؛ ChatGPT، Midjourney، Jasper و سایر ابزارهای AI از طریق مستر پریمیوم هاب",
    category: "premium",
  },
  {
    id: "seo-account",
    label: "خرید اکانت ابزارهای سئو",
    labelEn: "SEO Tools Account",
    href: "/currency-payment/seo-account",
    icon: React.createElement(FaSearch, { className: "text-3xl sm:text-4xl md:text-5xl text-green-500" }),
    description: "خرید اکانت پریمیوم ابزارهای سئو؛ SEMrush، Ahrefs، KWFinder، MOZ و سایر ابزارها از طریق مستر پریمیوم هاب",
    category: "premium",
  },
  {
    id: "game-account",
    label: "خرید اکانت بازی",
    labelEn: "Game Account",
    href: "/currency-payment/game-account",
    icon: React.createElement(FaGamepad, { className: "text-3xl sm:text-4xl md:text-5xl text-green-500" }),
    description: "خرید اکانت‌های پریمیوم بازی؛ Xbox Game Pass، PlayStation Plus، Steam، Epic Games و سایر پلتفرم‌ها از طریق مستر پریمیوم هاب",
    category: "premium",
  },
  {
    id: "software-account",
    label: "خرید اکانت اورجینال نرم افزار",
    labelEn: "Software Account",
    href: "/currency-payment/software-account",
    icon: React.createElement(MdCode, { className: "text-3xl sm:text-4xl md:text-5xl text-green-500" }),
    description: "خرید اکانت نرم‌افزارهای اورجینال",
    category: "premium",
  },
  {
    id: "language-exam",
    label: "ثبت نام آزمون زبان",
    labelEn: "Language Exam",
    href: "/currency-payment/language-exam",
    icon: React.createElement(HiAcademicCap, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "ثبت نام و پرداخت هزینه آزمون‌های زبان؛ IELTS، TOEFL، PTE، GRE، Duolingo و سایر آزمون‌ها از طریق مستر پریمیوم هاب",
    category: "education",
  },
  {
    id: "student-payment",
    label: "پرداخت دانشجویی",
    labelEn: "Student Payment",
    href: "/currency-payment/student-payment",
    icon: React.createElement(HiAcademicCap, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "پرداخت هزینه‌های دانشجویی؛ شهریه، خوابگاه، اپلیکیشن فی، WES و فعالیت‌های علمی بین‌المللی از طریق مستر پریمیوم هاب",
    category: "education",
  },
  {
    id: "international-exam",
    label: "آزمونهای بین المللی",
    labelEn: "International Exams",
    href: "/currency-payment/international-exam",
    icon: React.createElement(HiGlobe, { className: "text-3xl sm:text-4xl md:text-5xl text-[#ff5538]" }),
    description: "ثبت نام و پرداخت آزمون‌های بین‌المللی؛ GMAT، USMLE، PMP، IMAT، SAT، Prometric، ICF، CFA و آزمون‌های زبان از طریق مستر پریمیوم هاب",
    category: "education",
  },
  {
    id: "international-sim",
    label: "سیم کارت بین المللی",
    labelEn: "International SIM Card",
    href: "/currency-payment/international-sim",
    icon: React.createElement(MdSimCard, { className: "text-3xl sm:text-4xl md:text-5xl text-blue-500" }),
    description: "خرید سیم کارت بین‌المللی",
    category: "international",
  },
  {
    id: "virtual-number",
    label: "شماره مجازی",
    labelEn: "Virtual Number",
    href: "/currency-payment/virtual-number",
    icon: React.createElement(MdPhone, { className: "text-3xl sm:text-4xl md:text-5xl text-blue-500" }),
    description: "خرید شماره مجازی",
    category: "international",
  },
  {
    id: "domain",
    label: "خرید دامنه",
    labelEn: "Domain Purchase",
    href: "/currency-payment/domain",
    icon: React.createElement(MdDomain, { className: "text-3xl sm:text-4xl md:text-5xl text-blue-500" }),
    description: "خرید دامنه از وب‌سایت‌های معتبر خارجی مثل GoDaddy، Name.com و سایر ثبت‌کنندگان بین‌المللی",
    category: "international",
  },
  {
    id: "host",
    label: "خرید هاست",
    labelEn: "Host Purchase",
    href: "/currency-payment/host",
    icon: React.createElement(MdCloud, { className: "text-3xl sm:text-4xl md:text-5xl text-blue-500" }),
    description: "هاست خارجی برای راه‌اندازی وب‌سایت‌های حرفه‌ای؛ خرید از ارائه‌دهندگان معتبر با کیفیت بالا و پشتیبانی ۲۴ ساعته",
    category: "international",
  },
  {
    id: "amazon",
    label: "خرید از آمازون",
    labelEn: "Amazon Purchase",
    href: "/currency-payment/amazon",
    icon: React.createElement(SiAmazon, { className: "text-3xl sm:text-4xl md:text-5xl text-[#FF9900]" }),
    description: "خرید کالا از فروشگاه اینترنتی آمازون با تحویل درب منزل؛ خرید از آمازون انگلیس، آمریکا، کانادا و سایر کشورها از طریق مستر پریمیوم هاب",
    category: "international",
  },
  {
    id: "trendyol",
    label: "خرید از ترندیول ترکیه",
    labelEn: "Trendyol Turkey",
    href: "/currency-payment/trendyol",
    icon: React.createElement(BiShoppingBag, { className: "text-3xl sm:text-4xl md:text-5xl text-red-500" }),
    description: "خرید از ترندیول ترکیه با تحویل درب منزل؛ پوشاک، الکترونیک، عطر و ادکلن و سایر دسته‌بندی‌ها از طریق مستر پریمیوم هاب",
    category: "international",
  },
];

export const serviceCategories = [
  { id: "all", label: "همه خدمات", value: "all" },
  { id: "payment", label: "پرداخت", value: "payment" },
  { id: "travel", label: "مسافرتی", value: "travel" },
  { id: "education", label: "دانشگاهی", value: "education" },
  { id: "crypto", label: "ارز دیجیتال", value: "crypto" },
  { id: "other", label: "سایر", value: "other" },
];

